export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";
export const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS";
export const MOVIE_LIST_FAIL = "MOVIE_LIST_FAIL";

export const MOVIE_FEATURED_REQUEST = "MOVIE_FEATURED_REQUEST";
export const MOVIE_FEATURED_SUCCESS = "MOVIE_FEATURED_SUCCESS";
export const MOVIE_FEATURED_FAIL = "MOVIE_FEATURED_FAIL";
